version: '3.8'

services:
  template-db:
    image: postgres:16
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: template
      POSTGRES_DB: public
    volumes:
      - /tmp/data/pg-template:/var/lib/postgresql/data
    networks:
      - dev-template

networks:
  dev-template:
